ClassAndModuleChildren:
  EnforcedStyle: compact

ClassVars:
  Description: 'Avoid the use of class variables.'
  Enabled: false

ClassAndModuleChildren:
  EnforcedStyle: compact

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

DoubleNegation:
  Enabled: false

EmptyLines:
  Description: "Don't use several empty lines in a row."
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/ColonMethodCall:
  Description: 'Do not use :: for method call.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#double-colons'
  Enabled: false

Style/EmptyLines:
  Enabled: false
